version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      # - |
      #   ROCKET_DATABASES={
      #     postgres={url=postgres://postgres:postgres@postgres/app_db},
      #     redis={url=redis://redis:6379}
      #   }
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_USERNAME=paris.liakos@gmail.com
      # - SMTP_PASSWORD=okks qghu trly qwot
      # - FOO
    ports:
      - 8000:8000
    volumes:
      - ./:/app/

